''' <summary>
''' Load configuration (JSON format).
''' </summary>
Public Class ConfigStructure
    Property GeneralSilentMode As Boolean = True
    Property GeneralAutoRestart As Boolean = True
    Property GeneralAutoRestartHourInterval As Integer
        Get
            If _GeneralAutoRestartHourInterval > 24 Then 'max value is 24
                Return 24
            Else
                Return _GeneralAutoRestartHourInterval
            End If
        End Get
        Set(value As Integer)
            If value > 24 Then
                _GeneralAutoRestartHourInterval = 24
            Else
                _GeneralAutoRestartHourInterval = value
            End If
        End Set
    End Property
    Private _GeneralAutoRestartHourInterval As Integer = 1 'in hours

    Property WebApiPort As Integer = 80
    Property WebApiSelfHost As Boolean = False
    Public ReadOnly WebApiRandomPort As Boolean = True 'not used
    Property WebApiDir As String = "Web"

    Property Url As String = "" 'leave empty to use URI generated by ngrok, if not empty, ngrok will not be used.
    Property UrlPort As String = ""
    Property UrlAutoIP As Boolean = False
    ''' <summary>
    ''' Use Url2 in main program instead of Url.
    ''' </summary>
    ReadOnly Property Url2 As String
        Get
            Dim strUrl As String = ""
            If UrlAutoIP Then
                strUrl = Utility.GetPublicIP
                If strUrl.IsEmpty Then Throw New ApplicationException("Failed to retrieve public IP.")
            Else
                strUrl = Me.Url
            End If

            If Not Me.UrlPort.IsEmpty And Not strUrl.IsEmpty Then
                'make sure that URL ends with alphanumeric.
                Static regexUrl As New System.Text.RegularExpressions.Regex(".*[\w]$", System.Text.RegularExpressions.RegexOptions.IgnoreCase Or System.Text.RegularExpressions.RegexOptions.IgnorePatternWhitespace)
                If regexUrl.IsMatch(strUrl) Then
                    strUrl = strUrl & ":" & UrlPort
                End If
            End If

            Return strUrl
        End Get
    End Property
    ''' <summary>
    ''' Determine whether to use ngrok instead of Url property.
    ''' </summary>
    ReadOnly Property UseNgrokUrl As Boolean
        Get
            'if Url is empty and not using url auto ip, generate it using ngrok.
            Return Url.IsEmpty And UrlAutoIP = False
        End Get
    End Property

    Property NgrokPort As Integer = 4040
    Property NgrokUseSSL As Boolean = False
    Public ReadOnly NgrokRandomPort As Boolean = True 'not used
    Property NgrokSubdomain As String = ""
    Property NgrokAuthToken As String = ""

    Property Debug As Boolean

    Property ModuleProcessInterval As Integer = 1000 'default 1 second, used in WebApi's ModuleService as well with min value = 1
    Property CheckConnectionInterval As Integer = 600000 'default 10 minutes

    Property ErrEmail As String
    Property ErrPass As String
    Property ErrHost As String
    Property ErrSSL As Boolean = False
    Property ErrPort As Integer = 587
    Property ErrRecipient As String

    Property Suspended As Boolean 'if account is suspended, this value will be true and user will not be able to sync data with server.
    Property SyncOnce As Boolean 'executed by ModulesService in WebApi once.

    Property ResetIisOnLoad As Boolean 'developer can use this to automatically kill iisexpress to avoid hogging port.
End Class